import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'O garoto do blog - Meu primeiro blog',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang='pt-br' className='no-touch light'>
      <body>{children}</body>
    </html>
  );
}
